spring:
  application:
    name: blogs

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/blogs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Server Configuration
server:
  port: 8080

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Application Security Configuration
application:
  security:
    jwt:
      secret: ${JWT_SECRET:TmV3U2VjcmV0S2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzMTIzNDU2Nzg=}
      expiration: 86400000     # 24 hours
      refresh-token:
        expiration: 604800000  # 7 days